shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

branches:
  except:
    - /pr\/.+/


install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  
    ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\Training

build_script:
  - mkdir build && cd build
  - mkdir array && mkdir forward_list && mkdir tuple && mkdir unordered_map
  - cd array && cmake ../../array && make && ./array && cd ..
  - cd forward_list && cmake ../../forward_list && make && ./forward_list && cd ..
  - cd tuple && cmake ../../tuple && make && ./tuple && cd ..
  - cd unordered_map && cmake ../../unordered_map && make && ./unordered_map && cd ..

