shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

branches:
  except:
    - /pr\/.+/


install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version
  
    ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.0-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps\cmake > nul
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\Training

build_script:
  - mkdir build && cd build
  - mkdir array && cd array && cmake -GNinja ../../array && ninja && array && cd ..
  - mkdir tuple && cd tuple && cmake -GNinja ../../tuple && ninja && tuple && cd ..
  - mkdir chrono && cd chrono && cmake -GNinja ../../chrono && ninja && chrono && cd ..
  - mkdir cstdint && cd cstdint && cmake -GNinja ../../cstdint && ninja && cstdint && cd ..
  - mkdir type_traits && cd type_traits && cmake -GNinja ../../type_traits && ninja && type_traits && cd ..
  - mkdir forward_list && cd forward_list && cmake -GNinja ../../forward_list && ninja && forward_list && cd ..
  - mkdir unordered_map && cd unordered_map && cmake -GNinja ../../unordered_map && ninja && unordered_map && cd ..
  - mkdir unordered_set && cd unordered_set && cmake -GNinja ../../unordered_set && ninja && unordered_set && cd ..
  - mkdir initializer_list && cd initializer_list && cmake -GNinja ../../initializer_list && ninja && initializer_list && cd ..

